### ISSUE TITLE
structures plot : color only mutated node

### ISSUE THREAD

**Issue by martin-raden** [fabriziocosta/RaSE#19]
- [ ] position annotation (see #2)
- [ ] mutated node in red (see #2)
- [ ] mutation and wildtype letter for mutated node (see #2)
- [ ] all other nodes in white
